{-# LANGUAGE DeriveDataTypeable #-}
{-# OPTIONS_GHC -fno-warn-missing-fields #-}
{-# OPTIONS_GHC -fno-warn-missing-signatures #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-----------------------------------------------------------------
-- Autogenerated by Thrift Compiler (0.7.0)                      --
--                                                             --
-- DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING --
-----------------------------------------------------------------

module Limits_Consts where
import Prelude ( Bool(..), Enum, Double, String, Maybe(..),
                 Eq, Show, Ord,
                 return, length, IO, fromIntegral, fromEnum, toEnum,
                 (&&), (||), (==), (++), ($), (-) )

import Control.Exception
import Data.ByteString.Lazy
import Data.Int
import Data.Typeable ( Typeable )
import qualified Data.Map as Map
import qualified Data.Set as Set

import Thrift


import Limits_Types
eDAM_ATTRIBUTE_LEN_MIN :: Int32
eDAM_ATTRIBUTE_LEN_MIN = (1 :: Int32)

eDAM_ATTRIBUTE_LEN_MAX :: Int32
eDAM_ATTRIBUTE_LEN_MAX = (4096 :: Int32)

eDAM_ATTRIBUTE_REGEX :: String
eDAM_ATTRIBUTE_REGEX = "^[^\\p{Cc}\\p{Zl}\\p{Zp}]{1,4096}$"

eDAM_ATTRIBUTE_LIST_MAX :: Int32
eDAM_ATTRIBUTE_LIST_MAX = (100 :: Int32)

eDAM_GUID_LEN_MIN :: Int32
eDAM_GUID_LEN_MIN = (36 :: Int32)

eDAM_GUID_LEN_MAX :: Int32
eDAM_GUID_LEN_MAX = (36 :: Int32)

eDAM_GUID_REGEX :: String
eDAM_GUID_REGEX = "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"

eDAM_EMAIL_LEN_MIN :: Int32
eDAM_EMAIL_LEN_MIN = (6 :: Int32)

eDAM_EMAIL_LEN_MAX :: Int32
eDAM_EMAIL_LEN_MAX = (255 :: Int32)

eDAM_EMAIL_LOCAL_REGEX :: String
eDAM_EMAIL_LOCAL_REGEX = "^[A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+(\\.[A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+)*$"

eDAM_EMAIL_DOMAIN_REGEX :: String
eDAM_EMAIL_DOMAIN_REGEX = "^[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*\\.([A-Za-z]{2,})$"

eDAM_EMAIL_REGEX :: String
eDAM_EMAIL_REGEX = "^[A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+(\\.[A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*\\.([A-Za-z]{2,})$"

eDAM_TIMEZONE_LEN_MIN :: Int32
eDAM_TIMEZONE_LEN_MIN = (1 :: Int32)

eDAM_TIMEZONE_LEN_MAX :: Int32
eDAM_TIMEZONE_LEN_MAX = (32 :: Int32)

eDAM_TIMEZONE_REGEX :: String
eDAM_TIMEZONE_REGEX = "^([A-Za-z_-]+(/[A-Za-z_-]+)*)|(GMT(-|\\+)[0-9]{1,2}(:[0-9]{2})?)$"

eDAM_MIME_LEN_MIN :: Int32
eDAM_MIME_LEN_MIN = (3 :: Int32)

eDAM_MIME_LEN_MAX :: Int32
eDAM_MIME_LEN_MAX = (255 :: Int32)

eDAM_MIME_REGEX :: String
eDAM_MIME_REGEX = "^[A-Za-z]+/[A-Za-z0-9._+-]+$"

eDAM_MIME_TYPE_GIF :: String
eDAM_MIME_TYPE_GIF = "image/gif"

eDAM_MIME_TYPE_JPEG :: String
eDAM_MIME_TYPE_JPEG = "image/jpeg"

eDAM_MIME_TYPE_PNG :: String
eDAM_MIME_TYPE_PNG = "image/png"

eDAM_MIME_TYPE_WAV :: String
eDAM_MIME_TYPE_WAV = "audio/wav"

eDAM_MIME_TYPE_MP3 :: String
eDAM_MIME_TYPE_MP3 = "audio/mpeg"

eDAM_MIME_TYPE_AMR :: String
eDAM_MIME_TYPE_AMR = "audio/amr"

eDAM_MIME_TYPE_INK :: String
eDAM_MIME_TYPE_INK = "application/vnd.evernote.ink"

eDAM_MIME_TYPE_PDF :: String
eDAM_MIME_TYPE_PDF = "application/pdf"

eDAM_MIME_TYPE_DEFAULT :: String
eDAM_MIME_TYPE_DEFAULT = "application/octet-stream"

eDAM_MIME_TYPES :: Set.Set String
eDAM_MIME_TYPES = (Set.fromList ["image/gif","image/jpeg","image/png","audio/wav","audio/mpeg","audio/amr","application/vnd.evernote.ink","application/pdf"])

eDAM_COMMERCE_SERVICE_GOOGLE :: String
eDAM_COMMERCE_SERVICE_GOOGLE = "Google"

eDAM_COMMERCE_SERVICE_PAYPAL :: String
eDAM_COMMERCE_SERVICE_PAYPAL = "Paypal"

eDAM_COMMERCE_SERVICE_GIFT :: String
eDAM_COMMERCE_SERVICE_GIFT = "Gift"

eDAM_COMMERCE_SERVICE_TRIALPAY :: String
eDAM_COMMERCE_SERVICE_TRIALPAY = "TrialPay"

eDAM_COMMERCE_SERVICE_TRIAL :: String
eDAM_COMMERCE_SERVICE_TRIAL = "Trial"

eDAM_COMMERCE_SERVICE_GROUP :: String
eDAM_COMMERCE_SERVICE_GROUP = "Group"

eDAM_COMMERCE_SERVICE_CYBERSOURCE :: String
eDAM_COMMERCE_SERVICE_CYBERSOURCE = "CYBERSRC"

eDAM_COMMERCE_DEFAULT_CURRENCY_COUNTRY_CODE :: String
eDAM_COMMERCE_DEFAULT_CURRENCY_COUNTRY_CODE = "USD"

eDAM_SEARCH_QUERY_LEN_MIN :: Int32
eDAM_SEARCH_QUERY_LEN_MIN = (0 :: Int32)

eDAM_SEARCH_QUERY_LEN_MAX :: Int32
eDAM_SEARCH_QUERY_LEN_MAX = (1024 :: Int32)

eDAM_SEARCH_QUERY_REGEX :: String
eDAM_SEARCH_QUERY_REGEX = "^[^\\p{Cc}\\p{Zl}\\p{Zp}]{0,1024}$"

eDAM_HASH_LEN :: Int32
eDAM_HASH_LEN = (16 :: Int32)

eDAM_USER_USERNAME_LEN_MIN :: Int32
eDAM_USER_USERNAME_LEN_MIN = (1 :: Int32)

eDAM_USER_USERNAME_LEN_MAX :: Int32
eDAM_USER_USERNAME_LEN_MAX = (64 :: Int32)

eDAM_USER_USERNAME_REGEX :: String
eDAM_USER_USERNAME_REGEX = "^[a-z0-9]([a-z0-9_-]{0,62}[a-z0-9])?$"

eDAM_USER_NAME_LEN_MIN :: Int32
eDAM_USER_NAME_LEN_MIN = (1 :: Int32)

eDAM_USER_NAME_LEN_MAX :: Int32
eDAM_USER_NAME_LEN_MAX = (255 :: Int32)

eDAM_USER_NAME_REGEX :: String
eDAM_USER_NAME_REGEX = "^[^\\p{Cc}\\p{Zl}\\p{Zp}]{1,255}$"

eDAM_TAG_NAME_LEN_MIN :: Int32
eDAM_TAG_NAME_LEN_MIN = (1 :: Int32)

eDAM_TAG_NAME_LEN_MAX :: Int32
eDAM_TAG_NAME_LEN_MAX = (100 :: Int32)

eDAM_TAG_NAME_REGEX :: String
eDAM_TAG_NAME_REGEX = "^[^,\\p{Cc}\\p{Z}]([^,\\p{Cc}\\p{Zl}\\p{Zp}]{0,98}[^,\\p{Cc}\\p{Z}])?$"

eDAM_NOTE_TITLE_LEN_MIN :: Int32
eDAM_NOTE_TITLE_LEN_MIN = (1 :: Int32)

eDAM_NOTE_TITLE_LEN_MAX :: Int32
eDAM_NOTE_TITLE_LEN_MAX = (255 :: Int32)

eDAM_NOTE_TITLE_REGEX :: String
eDAM_NOTE_TITLE_REGEX = "^[^\\p{Cc}\\p{Z}]([^\\p{Cc}\\p{Zl}\\p{Zp}]{0,253}[^\\p{Cc}\\p{Z}])?$"

eDAM_NOTE_CONTENT_LEN_MIN :: Int32
eDAM_NOTE_CONTENT_LEN_MIN = (0 :: Int32)

eDAM_NOTE_CONTENT_LEN_MAX :: Int32
eDAM_NOTE_CONTENT_LEN_MAX = (5242880 :: Int32)

eDAM_NOTEBOOK_NAME_LEN_MIN :: Int32
eDAM_NOTEBOOK_NAME_LEN_MIN = (1 :: Int32)

eDAM_NOTEBOOK_NAME_LEN_MAX :: Int32
eDAM_NOTEBOOK_NAME_LEN_MAX = (100 :: Int32)

eDAM_NOTEBOOK_NAME_REGEX :: String
eDAM_NOTEBOOK_NAME_REGEX = "^[^\\p{Cc}\\p{Z}]([^\\p{Cc}\\p{Zl}\\p{Zp}]{0,98}[^\\p{Cc}\\p{Z}])?$"

eDAM_NOTEBOOK_STACK_LEN_MIN :: Int32
eDAM_NOTEBOOK_STACK_LEN_MIN = (1 :: Int32)

eDAM_NOTEBOOK_STACK_LEN_MAX :: Int32
eDAM_NOTEBOOK_STACK_LEN_MAX = (100 :: Int32)

eDAM_NOTEBOOK_STACK_REGEX :: String
eDAM_NOTEBOOK_STACK_REGEX = "^[^\\p{Cc}\\p{Z}]([^\\p{Cc}\\p{Zl}\\p{Zp}]{0,98}[^\\p{Cc}\\p{Z}])?$"

eDAM_PUBLISHING_URI_LEN_MIN :: Int32
eDAM_PUBLISHING_URI_LEN_MIN = (1 :: Int32)

eDAM_PUBLISHING_URI_LEN_MAX :: Int32
eDAM_PUBLISHING_URI_LEN_MAX = (255 :: Int32)

eDAM_PUBLISHING_URI_REGEX :: String
eDAM_PUBLISHING_URI_REGEX = "^[a-zA-Z0-9.~_+-]{1,255}$"

eDAM_PUBLISHING_URI_PROHIBITED :: Set.Set String
eDAM_PUBLISHING_URI_PROHIBITED = (Set.fromList [".."])

eDAM_PUBLISHING_DESCRIPTION_LEN_MIN :: Int32
eDAM_PUBLISHING_DESCRIPTION_LEN_MIN = (1 :: Int32)

eDAM_PUBLISHING_DESCRIPTION_LEN_MAX :: Int32
eDAM_PUBLISHING_DESCRIPTION_LEN_MAX = (200 :: Int32)

eDAM_PUBLISHING_DESCRIPTION_REGEX :: String
eDAM_PUBLISHING_DESCRIPTION_REGEX = "^[^\\p{Cc}\\p{Z}]([^\\p{Cc}\\p{Zl}\\p{Zp}]{0,198}[^\\p{Cc}\\p{Z}])?$"

eDAM_SAVED_SEARCH_NAME_LEN_MIN :: Int32
eDAM_SAVED_SEARCH_NAME_LEN_MIN = (1 :: Int32)

eDAM_SAVED_SEARCH_NAME_LEN_MAX :: Int32
eDAM_SAVED_SEARCH_NAME_LEN_MAX = (100 :: Int32)

eDAM_SAVED_SEARCH_NAME_REGEX :: String
eDAM_SAVED_SEARCH_NAME_REGEX = "^[^\\p{Cc}\\p{Z}]([^\\p{Cc}\\p{Zl}\\p{Zp}]{0,98}[^\\p{Cc}\\p{Z}])?$"

eDAM_USER_PASSWORD_LEN_MIN :: Int32
eDAM_USER_PASSWORD_LEN_MIN = (6 :: Int32)

eDAM_USER_PASSWORD_LEN_MAX :: Int32
eDAM_USER_PASSWORD_LEN_MAX = (64 :: Int32)

eDAM_USER_PASSWORD_REGEX :: String
eDAM_USER_PASSWORD_REGEX = "^[A-Za-z0-9!#$%&'()*+,./:;<=>?@^_`{|}~\\[\\]\\\\-]{6,64}$"

eDAM_NOTE_TAGS_MAX :: Int32
eDAM_NOTE_TAGS_MAX = (100 :: Int32)

eDAM_NOTE_RESOURCES_MAX :: Int32
eDAM_NOTE_RESOURCES_MAX = (1000 :: Int32)

eDAM_USER_TAGS_MAX :: Int32
eDAM_USER_TAGS_MAX = (100000 :: Int32)

eDAM_USER_SAVED_SEARCHES_MAX :: Int32
eDAM_USER_SAVED_SEARCHES_MAX = (100 :: Int32)

eDAM_USER_NOTES_MAX :: Int32
eDAM_USER_NOTES_MAX = (100000 :: Int32)

eDAM_USER_NOTEBOOKS_MAX :: Int32
eDAM_USER_NOTEBOOKS_MAX = (250 :: Int32)

eDAM_USER_RECENT_MAILED_ADDRESSES_MAX :: Int32
eDAM_USER_RECENT_MAILED_ADDRESSES_MAX = (10 :: Int32)

eDAM_USER_MAIL_LIMIT_DAILY_FREE :: Int32
eDAM_USER_MAIL_LIMIT_DAILY_FREE = (50 :: Int32)

eDAM_USER_MAIL_LIMIT_DAILY_PREMIUM :: Int32
eDAM_USER_MAIL_LIMIT_DAILY_PREMIUM = (200 :: Int32)

eDAM_USER_UPLOAD_LIMIT_FREE :: Int64
eDAM_USER_UPLOAD_LIMIT_FREE = (62914560 :: Int64)

eDAM_USER_UPLOAD_LIMIT_PREMIUM :: Int64
eDAM_USER_UPLOAD_LIMIT_PREMIUM = (1073741824 :: Int64)

eDAM_NOTE_SIZE_MAX_FREE :: Int32
eDAM_NOTE_SIZE_MAX_FREE = (26214400 :: Int32)

eDAM_NOTE_SIZE_MAX_PREMIUM :: Int32
eDAM_NOTE_SIZE_MAX_PREMIUM = (52428800 :: Int32)

eDAM_RESOURCE_SIZE_MAX_FREE :: Int32
eDAM_RESOURCE_SIZE_MAX_FREE = (26214400 :: Int32)

eDAM_RESOURCE_SIZE_MAX_PREMIUM :: Int32
eDAM_RESOURCE_SIZE_MAX_PREMIUM = (52428800 :: Int32)

eDAM_USER_LINKED_NOTEBOOK_MAX :: Int32
eDAM_USER_LINKED_NOTEBOOK_MAX = (100 :: Int32)

eDAM_NOTEBOOK_SHARED_NOTEBOOK_MAX :: Int32
eDAM_NOTEBOOK_SHARED_NOTEBOOK_MAX = (250 :: Int32)

