{-# LANGUAGE DeriveDataTypeable #-}
{-# OPTIONS_GHC -fno-warn-missing-fields #-}
{-# OPTIONS_GHC -fno-warn-missing-signatures #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-----------------------------------------------------------------
-- Autogenerated by Thrift Compiler (0.7.0)                      --
--                                                             --
-- DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING --
-----------------------------------------------------------------

module Types_Consts where
import Prelude ( Bool(..), Enum, Double, String, Maybe(..),
                 Eq, Show, Ord,
                 return, length, IO, fromIntegral, fromEnum, toEnum,
                 (&&), (||), (==), (++), ($), (-) )

import Control.Exception
import Data.ByteString.Lazy
import Data.Int
import Data.Typeable ( Typeable )
import qualified Data.Map as Map
import qualified Data.Set as Set

import Thrift

import qualified Limits_Types


import Types_Types
eDAM_NOTE_SOURCE_WEB_CLIP :: String
eDAM_NOTE_SOURCE_WEB_CLIP = "web.clip"

eDAM_NOTE_SOURCE_MAIL_CLIP :: String
eDAM_NOTE_SOURCE_MAIL_CLIP = "mail.clip"

eDAM_NOTE_SOURCE_MAIL_SMTP_GATEWAY :: String
eDAM_NOTE_SOURCE_MAIL_SMTP_GATEWAY = "mail.smtp"

