{-# LANGUAGE DeriveDataTypeable #-}
{-# OPTIONS_GHC -fno-warn-missing-fields #-}
{-# OPTIONS_GHC -fno-warn-missing-signatures #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-----------------------------------------------------------------
-- Autogenerated by Thrift Compiler (0.7.0)                      --
--                                                             --
-- DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING --
-----------------------------------------------------------------

module UserStore_Iface where
import Prelude ( Bool(..), Enum, Double, String, Maybe(..),
                 Eq, Show, Ord,
                 return, length, IO, fromIntegral, fromEnum, toEnum,
                 (&&), (||), (==), (++), ($), (-) )

import Control.Exception
import Data.ByteString.Lazy
import Data.Int
import Data.Typeable ( Typeable )
import qualified Data.Map as Map
import qualified Data.Set as Set

import Thrift

import qualified Types_Types
import qualified Errors_Types


import UserStore_Types

class UserStore_Iface a where
  checkVersion :: a -> Maybe String -> Maybe Int16 -> Maybe Int16 -> IO Bool
  authenticate :: a -> Maybe String -> Maybe String -> Maybe String -> Maybe String -> IO AuthenticationResult
  refreshAuthentication :: a -> Maybe String -> IO AuthenticationResult
  getUser :: a -> Maybe String -> IO Types_Types.User
  getPublicUserInfo :: a -> Maybe String -> IO PublicUserInfo
